version: '3'
services:
  app:
    image: itine/tamagotchi-authorization
    restart: always
    ports:
    - "5001:80"
    depends_on:
    - db
  db:
    image: postgres:10.5
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: tamagochi
      POSTGRES_PASSWORD: root
    volumes:
    - "postgres-data-auth:/var/lib/postgresql/data"
  adminer:
    image: adminer:4
    restart: always
    ports:
    - "9999:8080"
volumes:
  postgres-data-auth:
    driver: local