version: '3.4'

services:
  db:
     image: postgres:10.5
     restart: always
     ports:
       - "5432:5432"

  tamagotchi.authorization:
    image: tamagotchiauthorization
    ports:
     - "5001:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"