swagger: '2.0'
info:
  version: v1
  title: TamagotchiAuth
  description: Application Documentation
  termsOfService: None
  contact:
    name: Sergey Alekseev
    url: github.com/itine
  license:
    name: MIT
    url: 'https://en.wikipedia.org/wiki/MIT_License'
paths:
  /Auth/Token:
    post:
      tags:
        - Auth
      operationId: AuthTokenPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: jsonBody
          in: body
          required: false
          schema:
            type: object
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult[String]'
  /Auth/Registration:
    post:
      tags:
        - Auth
      operationId: AuthRegistrationPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: jsonBody
          in: body
          required: false
          schema:
            type: object
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult[String]'
  /Auth/SendPageAccess:
    post:
      tags:
        - Auth
      operationId: AuthSendPageAccessPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: jsonBody
          in: body
          required: false
          schema:
            type: object
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult[String]'
  /Auth/PasswordRecovery:
    post:
      tags:
        - Auth
      operationId: AuthPasswordRecoveryPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: jsonBody
          in: body
          required: false
          schema:
            type: object
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult[String]'
definitions:
  'ApiResult[String]':
    type: object
    properties:
      data:
        type: string
      error:
        $ref: '#/definitions/Error'
  Error:
    type: object
    properties:
      message:
        type: string
      code:
        type: string
