swagger: '2.0'
info:
  version: v1
  title: TamagotchiAuth
  description: Application Documentation
  termsOfService: None
  contact:
    name: Sergey Alekseev
    url: 'https://github.com/itine'
  license:
    name: MIT
    url: 'https://en.wikipedia.org/wiki/MIT_License'
paths:
  /auth/getversion:
    get:
      tags:
        - auth
      operationId: AuthGetversionGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  /auth/login:
    post:
      tags:
        - auth
      operationId: AuthLoginPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: loginModel
          in: body
          required: false
          schema:
            $ref: '#/definitions/LoginModel'
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult[string]'
  /auth/registration:
    post:
      tags:
        - auth
      operationId: AuthRegistrationPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: registrationModel
          in: body
          required: false
          schema:
            $ref: '#/definitions/RegistrationModel'
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult[string]'
  /auth/sendpageaccess:
    post:
      tags:
        - auth
      operationId: AuthSendpageaccessPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: sendingMailModel
          in: body
          required: false
          schema:
            $ref: '#/definitions/SendingMailModel'
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult[string]'
  /auth/passwordrecovery:
    post:
      tags:
        - auth
      operationId: AuthPasswordrecoveryPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: recoveryPasswordModel
          in: body
          required: false
          schema:
            $ref: '#/definitions/RecoveryPasswordModel'
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult[string]'
definitions:
  LoginModel:
    type: object
    properties:
      login:
        type: string
      password:
        type: string
  'ApiResult[String]':
    type: object
    properties:
      data:
        type: string
      errors:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/Error'
  Error:
    type: object
    properties:
      attr:
        type: string
      code:
        type: string
  RegistrationModel:
    type: object
    properties:
      login:
        type: string
      password:
        type: string
      passwordConfirm:
        type: string
      email:
        type: string
      pet:
        type: string
  SendingMailModel:
    type: object
    properties:
      login:
        type: string
      pageAccess:
        type: string
  RecoveryPasswordModel:
    type: object
    properties:
      login:
        type: string
      newPassword:
        type: string
