swagger: '2.0'
info:
  version: v1
  title: TamagotchiAuth
  description: Application Documentation
  termsOfService: None
  contact:
    name: Sergey Alekseev
    url: 'https://github.com/itine'
  license:
    name: MIT
    url: 'https://en.wikipedia.org/wiki/MIT_License'
paths:
  /version:
    get:
      tags:
        - auth
      operationId: VersionGet
      consumes: []
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/VersionModel'
       
  /login:
    post:
      tags:
        - auth
      operationId: LoginPost
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: loginModel
          in: body
          required: false
          schema:
            $ref: '#/definitions/LoginModel'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ApiResult'
        '400':
          description: Validation Error
        '401':
          description: Unauthorized
        '500':
          description: Server Error
  /register:
    post:
      tags:
        - auth
      operationId: RegisterPost
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: registrationModel
          in: body
          required: false
          schema:
            $ref: '#/definitions/RegistrationModel'
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult'
        '400':
          description: Validation Error
        '500':
          description: Server Error
 
  /password/recover:
    post:
      tags:
        - auth
      operationId: PasswordRecoverPost
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: sendingMailModel
          in: body
          required: false
          schema:
            $ref: '#/definitions/SendingMailModel'
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult'
        '400':
          description: Validation Error
        '500':
          description: Server Error
 
 
  /password/recover/confirm:
    post:
      tags:
        - auth
      operationId: PasswordRecoverConfirmPost
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: recoveryPasswordModel
          in: body
          required: false
          schema:
            $ref: '#/definitions/RecoveryPasswordModel'
      responses:
        '200':
          description: Success
          schema:
            $ref: '/definitions/ApiResult'
        '400':
          description: Validation Error
        '500':
          description: Server Error
 
definitions:
  VersionModel:
    required:
      - version
    type: object
    properties:
      version:
        type: string
  LoginModel:
    required:
      - login
      - password
    type: object
    properties:
      login:
        maxLength: 24
        minLength: 3
        type: string
      password:
        maxLength: 24
        minLength: 8
        type: string
  'ApiResult':
    type: object
    properties:
      data:
        type: string
      errors:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/Error'
  Error:
    type: object
    properties:
      attr:
        type: string
      code:
        type: string
  RegistrationModel:
    required:
      - login
      - password
      - passwordConfirm
      - email
    type: object
    properties:
      login:
        maxLength: 24
        minLength: 3
        type: string
      password:
        maxLength: 24
        minLength: 8
        type: string
      passwordConfirm:
        maxLength: 24
        minLength: 8
        type: string
      email:
        type: string
  SendingMailModel:
    required:
      - login
      - pageAccess
    type: object
    properties:
      login:
        maxLength: 24
        minLength: 3
        type: string
      pageAccess:
        type: string
  RecoveryPasswordModel:
    required:
      - login
      - newPassword
    type: object
    properties:
      login:
        maxLength: 24
        minLength: 3
        type: string
      newPassword:
        maxLength: 24
        minLength: 8
        type: string
